# Generated by Django 5.0.2 on 2024-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymodel',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='images/category/')),
            ],
            options={
                'db_table': 'catagory',
            },
        ),
    ]
