# Generated by Django 5.0.2 on 2024-05-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponmodel',
            fields=[
                ('Coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('Coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField()),
                ('minimum_amnt', models.IntegerField()),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='Districtmodel',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='statemodel',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Eventmodel',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(default='Active', max_length=50)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.couponmodel')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Restaurantmodel',
            fields=[
                ('Restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Restaurant_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('License', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=100)),
                ('Discription', models.TextField()),
                ('Phone_no', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='images/host/')),
                ('Host_status', models.CharField(default='Active', max_length=200)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.districtmodel')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Itemmodel',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('Quantity', models.CharField(max_length=200)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('Image', models.ImageField(upload_to='images/item/')),
                ('avg_rating', models.FloatField(default=0, null=True)),
                ('is_in_wishlist', models.BooleanField(default=False, null=True)),
                ('Status', models.CharField(default='Active', max_length=200)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.categorymodel')),
                ('Host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantmodel')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.statemodel'),
        ),
    ]
