# Generated by Django 5.0.2 on 2024-05-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addressmodel',
            fields=[
                ('Address_id', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('Pincode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200)),
                ('User_password', models.CharField(max_length=200)),
                ('User_mob', models.CharField(max_length=100)),
                ('User_email', models.EmailField(max_length=254, null=True)),
                ('User_create_at', models.DateTimeField(auto_now_add=True)),
                ('User_status', models.CharField(default='Active', max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='itemordermodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Orderid', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Status', models.CharField(default='Active', max_length=200)),
                ('Order_time', models.DateTimeField(auto_now_add=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.addressmodel')),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.itemmodel')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'itemorder',
            },
        ),
        migrations.CreateModel(
            name='Deliveryusermodel',
            fields=[
                ('Delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Active', max_length=200)),
                ('Deliver_time', models.DateTimeField()),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.addressmodel')),
                ('Order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.itemordermodel')),
            ],
            options={
                'db_table': 'delivery_detail',
            },
        ),
        migrations.CreateModel(
            name='Userimagemodel',
            fields=[
                ('Image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='images/userimg')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'user_image',
            },
        ),
        migrations.CreateModel(
            name='Reviewmodel',
            fields=[
                ('Review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.itemmodel')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Paymentmethod', models.CharField(max_length=200)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.itemordermodel')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Cartmodel',
            fields=[
                ('Cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.itemmodel')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.couponmodel')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
        migrations.CreateModel(
            name='Wishlistmodel',
            fields=[
                ('Wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.itemmodel')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
    ]
